categories:
    - Ecology
owner: ecology 
remote_repository_url: https://github.com/galaxyecology/tools-ecology/tree/master/tools/regionalgam
homepage_url: https://github.com/RetoSchmucki/regionalGAM 
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for regionalGAM application {{ tool_name }}."
suite:
  name: suite_regionalgam
  description: Implementation of a method for compution abundance.
  long_description: Implementation of a method for computing an abundance index with the regional GAM approach, an extension of the two-stages model introduced by Dennis et al. (2013). This index offers the best performance for a wide range of sampling frequency, providing greater robustness and unbiased estimates compared to the popular linear interpolation approach (Schmucki et al. 2015).
